name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install flask
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run Flask app
      run: python app.py &
    - name: Install Nginx
      run: sudo apt-get update && sudo apt-get install nginx -y

    - name: Create Nginx configuration file
      run: |
        echo "server {
                listen 80;
                location / {
                  proxy_pass http://localhost:5000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                }
              }" | sudo tee /etc/nginx/sites-available/flask-app
    
    - name: Enable Nginx site
      run: sudo ln -s /etc/nginx/sites-available/flask-app /etc/nginx/sites-enabled/
    
    - name: Restart Nginx
      run: |
        sudo systemctl restart nginx
        systemctl status nginx.service
        journalctl -xeu nginx.service
    
        
